title: The Legolas Code
subtitle: A novel tool for 1D MHD spectroscopy
email: niels.claes@kuleuven.be
description: >-
  The Legolas code
baseurl: "/the-legolas-code"
url: "localhost:4000"
permalink: pretty

minimal_mistakes_skin: "air"
search: true

footer:
  links:
    - label: "The Legolas code on GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/n-claes/website_test

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock

# this is needed because sphinx creates directories with _ prepended, which
# are not copied by Jekyll.
keep_files:
  - content/src-docs/sphinx
